name: Deploy to EC2 Instance 

on:
  push:     
    branches:  
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: AWS credentials
        uses: appleboy/ssh-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY
          script: |
            export AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY

      - name: Copy files via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{  secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: dags/*
          target: /home/ubuntu/airflow/dags/
          strip_components: 1