name: Deploy to EC2 Instance 

on:
  push:     
    branches:  
      - master
    paths: 
      - 'dags/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{  secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
        with:
          source: my_test_dag.py
          target: /home/ubuntu/airflow/dags/